version: '3.8'
services:
  app:
    build:
      context: .
    container_name: python_web_app
    ports:
      - "5000:5000"  # Flask app will continue to run on port 5000 inside the container
  
  nginx:
    image: nginx
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom nginx.conf
    ports:
      - "5001:80"  # Expose Nginx on port 5001 on the host, forwarding to internal port 80 in the container
